CREATE TABLE tst01.Product
(
    id int(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    title varchar(500),
    citilinkID int(11),
    citilinkURL varchar(500),
    synonyms text,
    keywordID int(11)
);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (1, 'Смартфон SAMSUNG Galaxy S7 32Gb,  SM-G930FD,  черный', 357582, 'https://www.citilink.ru/catalog/mobile/cell_phones/357582/', 'SM-G930FD; G930FD;SAMSUNG Galaxy S7 ', 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (2, 'Смартфон SAMSUNG Galaxy S7 32Gb,  SM-G930FD,  серебристый', 357583, 'https://www.citilink.ru/catalog/mobile/cell_phones/357583/', 'SM-G930FD; G930FD;SAMSUNG Galaxy S7 ', 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (3, 'Смартфон SAMSUNG Galaxy S7 Edge 32Gb,  SM-G935FD,  серебристый', 357586, 'https://www.citilink.ru/catalog/mobile/cell_phones/357586/', 'SM-G930FD; G930FD;SAMSUNG Galaxy S7 Edge', 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (4, 'Смартфон SAMSUNG Galaxy S7 Edge 32Gb,  SM-G935FD,  синий', 410094, 'https://www.citilink.ru/catalog/mobile/cell_phones/410094/', 'SM-G930FD; G930FD;SAMSUNG Galaxy S7 Edge', 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (5, 'Очки виртуальной реальности SAMSUNG Galaxy Gear VR SM-R323,  темно-синий', 388796, 'https://www.citilink.ru/catalog/mobile/phone_gadgets/virtualnye_ochki/388796/', null, 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (6, 'Очки виртуальной реальности SAMSUNG Galaxy Gear VR SM-R324,  темно-синий', 462039, 'https://www.citilink.ru/catalog/mobile/phone_gadgets/virtualnye_ochki/462039/', null, 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (7, 'Очки виртуальной реальности SAMSUNG Galaxy Gear VR SM-R325,  темно-синий', 494560, 'https://www.citilink.ru/catalog/mobile/phone_gadgets/virtualnye_ochki/494560/', 'dsfdsf sd f sdfs df', 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (8, 'Смартфон APPLE iPhone 7 Plus 128Gb,  MN4M2RU/A,  черный', 393698, 'https://www.citilink.ru/catalog/mobile/cell_phones/393698/', 'MN4M2RU; APPLE iPhone 7 Plus 128Gb', 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (9, 'Смартфон APPLE iPhone 6s Plus 32Gb,  MN2W2RU/A,  серебристый', 393561, 'https://www.citilink.ru/catalog/mobile/cell_phones/393561/', null, 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (10, 'Смартфон APPLE iPhone 7 256Gb,  MN992RU/A,  золотистый', 393693, 'https://www.citilink.ru/catalog/mobile/cell_phones/393693/', null, 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (11, 'Смартфон APPLE iPhone SE 128Gb,  MP882RU/A,  золотистый', 442051, 'https://www.citilink.ru/catalog/mobile/cell_phones/442051/', null, 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (12, 'Смартфон APPLE iPhone 7 256Gb,  MN972RU/A,  черный', 393691, 'https://www.citilink.ru/catalog/mobile/cell_phones/393691/', null, 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (13, 'Смартфон APPLE iPhone 7 256Gb,  MN9C2RU/A,  черный оникс', 393696, 'https://www.citilink.ru/catalog/mobile/cell_phones/393696/', null, 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (14, 'Смартфон APPLE iPhone SE 128Gb,  MP892RU/A,  розовое золото', 442054, 'https://www.citilink.ru/catalog/mobile/cell_phones/442054/', null, 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (15, 'Смартфон APPLE iPhone 8 256Gb,  MQ7E2RU/A,  золотистый', 499062, 'https://www.citilink.ru/catalog/mobile/cell_phones/499062/', null, 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (16, 'Смартфон APPLE iPhone 7 32Gb,  MQTX2RU/A,  черный оникс', 499045, 'https://www.citilink.ru/catalog/mobile/cell_phones/499045/', null, 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (17, 'Смартфон APPLE iPhone 8 64Gb,  MQ6J2RU/A,  золотистый', 499061, 'https://www.citilink.ru/catalog/mobile/cell_phones/499061/', null, 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (18, 'Смартфон APPLE iPhone 6 32Gb,  MQ3D2RU/A,  серый', 470887, 'https://www.citilink.ru/catalog/mobile/cell_phones/470887/', 'APPLE iPhone 6 32Gb; MQ3D2RU', 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (19, 'Док-станция BELKIN F8J183VFC00-APL,  Apple Watch Series 1, Series 2, Edition, Nike+, Hermes, iPhone', 377744, 'https://www.citilink.ru/catalog/mobile/cellphones_chargers/377744/', null, 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (20, 'Смартфон APPLE iPhone 6s Plus 128Gb,  MKUE2RU/A,  серебристый', 328084, 'https://www.citilink.ru/catalog/mobile/cell_phones/328084/', null, 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (21, 'Смартфон APPLE iPhone X 256Gb,  MQAF2RU/A,  серый', 499093, 'https://www.citilink.ru/catalog/mobile/cell_phones/499093/', null, 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (22, 'Смартфон APPLE iPhone X 64Gb,  MQAC2RU/A,  серый', 499091, 'https://www.citilink.ru/catalog/mobile/cell_phones/499091/', null, 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (23, 'Смартфон APPLE iPhone 7 Plus 128Gb,  MN4Q2RU/A,  золотистый', 393704, 'https://www.citilink.ru/catalog/mobile/cell_phones/393704/', null, 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (24, 'Смартфон APPLE iPhone 7 Plus 128Gb,  MN4U2RU/A,  розовое золото', 393705, 'https://www.citilink.ru/catalog/mobile/cell_phones/393705/', null, 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (25, 'Смартфон APPLE iPhone 7 Plus 128Gb,  MN4V2RU/A,  черный оникс', 393706, 'https://www.citilink.ru/catalog/mobile/cell_phones/393706/', null, 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (26, 'Смартфон APPLE iPhone X 256Gb,  MQAG2RU/A,  серебристый', 499094, 'https://www.citilink.ru/catalog/mobile/cell_phones/499094/', 'APPLE iPhone X 256Gb; MQAG2RU/A', 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (27, 'Смартфон APPLE iPhone 6s Plus 32Gb,  MN2V2RU/A,  серый', 393560, 'https://www.citilink.ru/catalog/mobile/cell_phones/393560/', null, 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (28, 'Смартфон APPLE iPhone 7 128Gb,  MN962RU/A,  черный оникс', 393688, 'https://www.citilink.ru/catalog/mobile/cell_phones/393688/', null, 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (29, 'Смартфон APPLE iPhone SE 128Gb,  MP862RU/A,  серый', 442049, 'https://www.citilink.ru/catalog/mobile/cell_phones/442049/', ' APPLE iPhone SE 128; MP862RU', 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (30, 'Смартфон APPLE iPhone 6s Plus 128Gb,  MKUF2RU/A,  золотистый', 328085, 'https://www.citilink.ru/catalog/mobile/cell_phones/328085/', null, 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (31, 'Смартфон APPLE iPhone 7 32Gb,  MN912RU/A,  розовое золото', 393680, 'https://www.citilink.ru/catalog/mobile/cell_phones/393680/', null, 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (32, 'Смартфон APPLE iPhone 7 128Gb,  MN922RU/A,  черный', 393683, 'https://www.citilink.ru/catalog/mobile/cell_phones/393683/', null, 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (33, 'Смартфон APPLE iPhone 6s Plus 128Gb,  MKUG2RU/A,  розовый', 328086, 'https://www.citilink.ru/catalog/mobile/cell_phones/328086/', ' APPLE iPhone 6s Plus; MKUG2RU', 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (34, 'Смартфон APPLE iPhone 7 128Gb,  MN942RU/A,  золотистый', 393685, 'https://www.citilink.ru/catalog/mobile/cell_phones/393685/', null, 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (35, 'Смартфон APPLE iPhone 7 128Gb,  MN932RU/A,  серебристый', 393684, 'https://www.citilink.ru/catalog/mobile/cell_phones/393684/', null, 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (36, 'Смартфон APPLE iPhone 6s Plus 128Gb,  MKUD2RU/A,  серый', 328083, 'https://www.citilink.ru/catalog/mobile/cell_phones/328083/', null, 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (37, 'Смартфон APPLE iPhone 7 128Gb,  MN952RU/A,  розовое золото', 393686, 'https://www.citilink.ru/catalog/mobile/cell_phones/393686/', null, 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (38, 'Смартфон APPLE iPhone 8 Plus 64Gb,  MQ8L2RU/A,  серый', 499077, 'https://www.citilink.ru/catalog/mobile/cell_phones/499077/', null, 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (39, 'Смартфон APPLE iPhone 8 256Gb,  MQ7D2RU/A,  серебристый', 499057, 'https://www.citilink.ru/catalog/mobile/cell_phones/499057/', null, 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (40, 'Смартфон APPLE iPhone 8 256Gb,  MQ7C2RU/A,  серый', 499056, 'https://www.citilink.ru/catalog/mobile/cell_phones/499056/', null, 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (41, 'Смартфон APPLE iPhone 8 64Gb,  MQ6H2RU/A,  серебристый', 499055, 'https://www.citilink.ru/catalog/mobile/cell_phones/499055/', null, 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (42, 'Смартфон APPLE iPhone 7 Plus 128Gb,  MN4P2RU/A,  серебристый', 393702, 'https://www.citilink.ru/catalog/mobile/cell_phones/393702/', null, 1);
INSERT INTO tst01.Product (id, title, citilinkID, citilinkURL, synonyms, keywordID) VALUES (43, 'Смартфон APPLE iPhone 7 Plus 32Gb,  MNQN2RU/A,  серебристый', 393714, 'https://www.citilink.ru/catalog/mobile/cell_phones/393714/', null, 1);